--
-- PostgreSQL database dump
--

\restrict 1rGwwGvwBFhfxZuDTDIJMXmGvlnex5DSWCgUp6Bv8KrNefEgkBGssUr1NYShukM

-- Dumped from database version 15.15 (Homebrew)
-- Dumped by pg_dump version 15.15 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: yaelfarber
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO yaelfarber;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: yaelfarber
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: yaelfarber
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO yaelfarber;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: yaelfarber
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: yaelfarber
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO yaelfarber;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: yaelfarber
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: yaelfarber
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO yaelfarber;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: yaelfarber
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO yaelfarber;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: yaelfarber
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: yaelfarber
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: yaelfarber
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO yaelfarber;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: yaelfarber
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_borrower; Type: TABLE; Schema: public; Owner: yaelfarber
--

CREATE TABLE public.core_borrower (
    borrower_id uuid NOT NULL,
    id_number character varying(20) NOT NULL,
    address character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id integer,
    trustee_id uuid,
    email character varying(254),
    first_name character varying(100),
    last_name character varying(100),
    phone character varying(20)
);


ALTER TABLE public.core_borrower OWNER TO yaelfarber;

--
-- Name: core_loanchecks; Type: TABLE; Schema: public; Owner: yaelfarber
--

CREATE TABLE public.core_loanchecks (
    loan_id uuid NOT NULL,
    amount numeric(10,2) NOT NULL,
    start_date date NOT NULL,
    status character varying(20) NOT NULL,
    form_file character varying(100),
    created_at timestamp with time zone NOT NULL,
    num_payments integer NOT NULL,
    check_details text,
    predefined_schedule boolean NOT NULL,
    borrower_id uuid NOT NULL,
    trustee_id uuid
);


ALTER TABLE public.core_loanchecks OWNER TO yaelfarber;

--
-- Name: core_loanstandingorder; Type: TABLE; Schema: public; Owner: yaelfarber
--

CREATE TABLE public.core_loanstandingorder (
    loan_id uuid NOT NULL,
    amount numeric(10,2) NOT NULL,
    start_date date NOT NULL,
    status character varying(20) NOT NULL,
    form_file character varying(100),
    created_at timestamp with time zone NOT NULL,
    monthly_amount numeric(10,2) NOT NULL,
    charge_day integer NOT NULL,
    stop_date date,
    borrower_id uuid NOT NULL,
    trustee_id uuid
);


ALTER TABLE public.core_loanstandingorder OWNER TO yaelfarber;

--
-- Name: core_payment; Type: TABLE; Schema: public; Owner: yaelfarber
--

CREATE TABLE public.core_payment (
    id uuid NOT NULL,
    object_id uuid NOT NULL,
    due_date date NOT NULL,
    amount numeric(10,2) NOT NULL,
    amount_paid numeric(10,2) NOT NULL,
    status character varying(10) NOT NULL,
    paid_at timestamp with time zone,
    check_number character varying(50),
    content_type_id integer NOT NULL
);


ALTER TABLE public.core_payment OWNER TO yaelfarber;

--
-- Name: core_role; Type: TABLE; Schema: public; Owner: yaelfarber
--

CREATE TABLE public.core_role (
    role_id uuid NOT NULL,
    name character varying(50) NOT NULL,
    description character varying(255),
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.core_role OWNER TO yaelfarber;

--
-- Name: core_trustee; Type: TABLE; Schema: public; Owner: yaelfarber
--

CREATE TABLE public.core_trustee (
    trustee_id uuid NOT NULL,
    community character varying(100) NOT NULL,
    notes text,
    user_id integer NOT NULL
);


ALTER TABLE public.core_trustee OWNER TO yaelfarber;

--
-- Name: core_userprofile; Type: TABLE; Schema: public; Owner: yaelfarber
--

CREATE TABLE public.core_userprofile (
    id bigint NOT NULL,
    phone character varying(20),
    role_id uuid,
    user_id integer NOT NULL
);


ALTER TABLE public.core_userprofile OWNER TO yaelfarber;

--
-- Name: core_userprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: yaelfarber
--

ALTER TABLE public.core_userprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_userprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: yaelfarber
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO yaelfarber;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: yaelfarber
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: yaelfarber
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO yaelfarber;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: yaelfarber
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: yaelfarber
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO yaelfarber;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: yaelfarber
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: yaelfarber
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO yaelfarber;

--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: yaelfarber
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: yaelfarber
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: yaelfarber
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add תפקיד	7	add_role
26	Can change תפקיד	7	change_role
27	Can delete תפקיד	7	delete_role
28	Can view תפקיד	7	view_role
29	Can add לווה	8	add_borrower
30	Can change לווה	8	change_borrower
31	Can delete לווה	8	delete_borrower
32	Can view לווה	8	view_borrower
33	Can add נאמן	9	add_trustee
34	Can change נאמן	9	change_trustee
35	Can delete נאמן	9	delete_trustee
36	Can view נאמן	9	view_trustee
37	Can add הלוואה (הוראת קבע)	10	add_loanstandingorder
38	Can change הלוואה (הוראת קבע)	10	change_loanstandingorder
39	Can delete הלוואה (הוראת קבע)	10	delete_loanstandingorder
40	Can view הלוואה (הוראת קבע)	10	view_loanstandingorder
41	Can add הלוואה (צ'קים)	11	add_loanchecks
42	Can change הלוואה (צ'קים)	11	change_loanchecks
43	Can delete הלוואה (צ'קים)	11	delete_loanchecks
44	Can view הלוואה (צ'קים)	11	view_loanchecks
45	Can add פרופיל משתמש	12	add_userprofile
46	Can change פרופיל משתמש	12	change_userprofile
47	Can delete פרופיל משתמש	12	delete_userprofile
48	Can view פרופיל משתמש	12	view_userprofile
49	Can add payment	13	add_payment
50	Can change payment	13	change_payment
51	Can delete payment	13	delete_payment
52	Can view payment	13	view_payment
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: yaelfarber
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1000000$4ztoOmOdyi2xBasKu70yNe$xqnxqcK2Iy3cOCwK4DlL0SpiQOzVvRxxNS7S4eMWLUk=	\N	t	admin1				t	t	2025-12-09 21:57:14.133311+02
2	pbkdf2_sha256$1000000$4ztoOmOdyi2xBasKu70yNe$xqnxqcK2Iy3cOCwK4DlL0SpiQOzVvRxxNS7S4eMWLUk=	\N	t	admin2				t	t	2025-12-09 21:57:14.135578+02
3	pbkdf2_sha256$1000000$TwheIX39GPODTixzmKJxtL$xalEttEbPwRLROsu4lTZ6MVi+y2zh9ir+wT66zcaQWY=	\N	f	trustee1				f	t	2025-12-09 21:57:14.136442+02
4	pbkdf2_sha256$1000000$TwheIX39GPODTixzmKJxtL$xalEttEbPwRLROsu4lTZ6MVi+y2zh9ir+wT66zcaQWY=	\N	f	trustee2				f	t	2025-12-09 21:57:14.137196+02
5	pbkdf2_sha256$1000000$TwheIX39GPODTixzmKJxtL$xalEttEbPwRLROsu4lTZ6MVi+y2zh9ir+wT66zcaQWY=	\N	f	trustee3				f	t	2025-12-09 21:57:14.137862+02
6	pbkdf2_sha256$1000000$kSkyzwiZwxV6e0rurACDkM$rvsPE5iop9LsqBBO9OgyJZTGx0yObMQp3yL+sjdqtbQ=	\N	f	borrower1				f	t	2025-12-09 21:57:14.138705+02
7	pbkdf2_sha256$1000000$kSkyzwiZwxV6e0rurACDkM$rvsPE5iop9LsqBBO9OgyJZTGx0yObMQp3yL+sjdqtbQ=	\N	f	borrower2				f	t	2025-12-09 21:57:14.139278+02
8	pbkdf2_sha256$1000000$kSkyzwiZwxV6e0rurACDkM$rvsPE5iop9LsqBBO9OgyJZTGx0yObMQp3yL+sjdqtbQ=	\N	f	borrower3				f	t	2025-12-09 21:57:14.139868+02
9	pbkdf2_sha256$1000000$lV6QK15LGz8toLVmBBKXP8$02UKNygai9XYawlWywonAt3YmAukKhzI6XYYfUf5W34=	\N	f	donor1				f	t	2025-12-09 21:57:14.140487+02
10	pbkdf2_sha256$1000000$lV6QK15LGz8toLVmBBKXP8$02UKNygai9XYawlWywonAt3YmAukKhzI6XYYfUf5W34=	\N	f	donor2				f	t	2025-12-09 21:57:14.140947+02
11	pbkdf2_sha256$1000000$dQtgiAVGCf2ud2OoRQXKaI$fygWi7pI95a68fjAGwT9ofvYyP3f0emcbjK+ahgkI1g=	2025-12-21 21:37:36.008611+02	t	yaelfarber				t	t	2025-12-21 21:25:31.545251+02
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: yaelfarber
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: yaelfarber
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: core_borrower; Type: TABLE DATA; Schema: public; Owner: yaelfarber
--

COPY public.core_borrower (borrower_id, id_number, address, created_at, user_id, trustee_id, email, first_name, last_name, phone) FROM stdin;
a1c69b17-05ff-40f2-8bc4-79b139803db2	878909394	Jerusalem	2026-01-14 10:21:49.518074+02	\N	00000000-0000-0000-0000-000000000001	noa@gmail.com	נעה	ישראלי	0501234567
00000000-0000-0000-0000-000000000001	123456781	רח׳ הר חומה 12, ירושלים	2025-01-01 02:00:00+02	6	00000000-0000-0000-0000-000000000001	avital@gmail.com	אביטל	כהן	0545673214
00000000-0000-0000-0000-000000000002	123456782	רח׳ יפו 35, ירושלים	2025-01-01 02:00:00+02	7	00000000-0000-0000-0000-000000000002	\N	רבקה	ישראלי	0553457616
00000000-0000-0000-0000-000000000003	123456783	רח׳ חב״ד 4, ירושלים	2025-01-01 02:00:00+02	8	00000000-0000-0000-0000-000000000003	sara@gmail.com	שרה	לוי	0549873457
843a1c13-df95-4f99-aad0-9db97635ab42	878572520	Jerusalem	2026-01-14 10:16:12.641675+02	\N	00000000-0000-0000-0000-000000000001	\N	משה	כהן	0501234567
96f1f395-9707-4097-a6e2-4cc3726bb566	878688469	Jerusalem	2026-01-14 10:18:08.662319+02	\N	00000000-0000-0000-0000-000000000001	\N	יצחק	לוי	0501234567
12c5c16e-8428-48b3-bd9c-1a11f6fe4c29	326770468	ירושלים	2026-01-07 10:46:09.22778+02	\N	00000000-0000-0000-0000-000000000001	y@gmail.com	יעל	פ	0556784567
2a3cd6f0-456a-4689-ac86-0051857bf6a2	456789123	ירושלים	2026-01-20 13:08:32.389158+02	\N	00000000-0000-0000-0000-000000000002	chaim@gmaiil.com	חיים	כהן	05556784532
bd155497-3dd7-49af-8f77-acd51a4dc54d	584013560	Jerusalem	2026-01-21 10:26:53.833352+02	\N	00000000-0000-0000-0000-000000000001		PW	MemberC_1768984013560	0501234567
f8bf0e9c-8741-4cc6-80c8-09b69795e1f1	584013475	Test Address 123	2026-01-21 10:26:56.141401+02	\N	00000000-0000-0000-0000-000000000001		PW	CreateC_1768984013475	0501234567
75e8bb42-69e3-4abc-8a13-23b9a3ae59a6	324567421	ירושלים	2026-01-21 11:16:21.329485+02	\N	00000000-0000-0000-0000-000000000001		הילה	ר	0555687577
\.


--
-- Data for Name: core_loanchecks; Type: TABLE DATA; Schema: public; Owner: yaelfarber
--

COPY public.core_loanchecks (loan_id, amount, start_date, status, form_file, created_at, num_payments, check_details, predefined_schedule, borrower_id, trustee_id) FROM stdin;
00000000-0000-0000-0000-000000000002	7500.00	2025-02-10	PENDING		2025-02-10 02:00:00+02	6	Checks pending approval	f	00000000-0000-0000-0000-000000000002	00000000-0000-0000-0000-000000000002
00000000-0000-0000-0000-000000000003	8200.00	2025-03-05	PAID		2025-03-05 02:00:00+02	8	Paid checks loan	t	00000000-0000-0000-0000-000000000003	00000000-0000-0000-0000-000000000003
7d2077bf-35cb-4c1b-9629-ca1ea01a3e0d	25000.00	2026-01-06	ACTIVE		2026-01-07 10:46:09.234189+02	25	\N	t	12c5c16e-8428-48b3-bd9c-1a11f6fe4c29	00000000-0000-0000-0000-000000000001
532a6ee1-8b69-469d-84a4-acdf25ca014c	30.00	2026-01-07	ACTIVE		2026-01-07 11:00:21.481336+02	1	\N	t	12c5c16e-8428-48b3-bd9c-1a11f6fe4c29	00000000-0000-0000-0000-000000000001
e651d84d-2551-4cf8-821c-fd84859a259b	1000.00	2026-02-15	ACTIVE		2026-01-14 10:16:12.859573+02	5	\N	t	843a1c13-df95-4f99-aad0-9db97635ab42	00000000-0000-0000-0000-000000000001
4108597c-02a5-4815-b3fe-1c229bcd5b50	1000.00	2026-02-15	ACTIVE		2026-01-14 10:18:08.670886+02	5	\N	t	96f1f395-9707-4097-a6e2-4cc3726bb566	00000000-0000-0000-0000-000000000001
b7fd0ace-a67c-46d0-9be3-98447a1c3bf5	1000.00	2026-02-15	ACTIVE		2026-01-14 10:21:49.520919+02	5	\N	t	a1c69b17-05ff-40f2-8bc4-79b139803db2	00000000-0000-0000-0000-000000000001
088f48d9-c503-4931-8bf3-cd643847ae58	25000.00	2026-02-01	ACTIVE		2026-01-20 12:57:33.729272+02	25	\N	t	12c5c16e-8428-48b3-bd9c-1a11f6fe4c29	00000000-0000-0000-0000-000000000001
6b0d57b5-b41b-4cad-9952-9e07f3f51d9a	1000.00	2026-02-15	ACTIVE		2026-01-21 10:26:54.296004+02	5	\N	t	bd155497-3dd7-49af-8f77-acd51a4dc54d	00000000-0000-0000-0000-000000000001
dd1ecf4c-f22b-4e7b-bb98-ff0fd5fd6294	1000.00	2026-02-15	ACTIVE		2026-01-21 10:26:56.149101+02	5	\N	t	f8bf0e9c-8741-4cc6-80c8-09b69795e1f1	00000000-0000-0000-0000-000000000001
00000000-0000-0000-0000-000000000001	5000.00	2025-02-01	PAID		2025-01-01 02:00:00+02	10	Demo checks	t	00000000-0000-0000-0000-000000000001	00000000-0000-0000-0000-000000000001
\.


--
-- Data for Name: core_loanstandingorder; Type: TABLE DATA; Schema: public; Owner: yaelfarber
--

COPY public.core_loanstandingorder (loan_id, amount, start_date, status, form_file, created_at, monthly_amount, charge_day, stop_date, borrower_id, trustee_id) FROM stdin;
00000000-0000-0000-0000-000000000001	3600.00	2025-01-15	ACTIVE		2025-01-15 02:00:00+02	300.00	12	\N	00000000-0000-0000-0000-000000000001	00000000-0000-0000-0000-000000000001
00000000-0000-0000-0000-000000000002	9000.00	2025-02-20	REJECTED		2025-02-20 02:00:00+02	750.00	5	\N	00000000-0000-0000-0000-000000000002	00000000-0000-0000-0000-000000000002
00000000-0000-0000-0000-000000000003	4200.00	2025-03-01	PENDING		2025-03-01 02:00:00+02	350.00	1	\N	00000000-0000-0000-0000-000000000003	00000000-0000-0000-0000-000000000003
319c190f-9504-4de4-b24b-3c7dff2f61f0	5000.00	2026-01-19	ACTIVE		2026-01-07 10:57:36.883979+02	1000.00	19	\N	12c5c16e-8428-48b3-bd9c-1a11f6fe4c29	00000000-0000-0000-0000-000000000002
80d74015-ad29-49b2-a6a5-808c41b9fe26	25000.00	2026-02-01	ACTIVE		2026-01-20 13:08:32.394404+02	1000.00	1	\N	2a3cd6f0-456a-4689-ac86-0051857bf6a2	00000000-0000-0000-0000-000000000001
97e351f8-a76d-48d5-81d6-b2ef3e15158b	25000.00	2026-01-21	ACTIVE		2026-01-21 11:16:21.333121+02	1000.00	21	\N	75e8bb42-69e3-4abc-8a13-23b9a3ae59a6	00000000-0000-0000-0000-000000000001
\.


--
-- Data for Name: core_payment; Type: TABLE DATA; Schema: public; Owner: yaelfarber
--

COPY public.core_payment (id, object_id, due_date, amount, amount_paid, status, paid_at, check_number, content_type_id) FROM stdin;
ae5f9e20-23c2-4403-8435-97a9993c63c4	7d2077bf-35cb-4c1b-9629-ca1ea01a3e0d	2026-05-06	1000.00	0.00	PENDING	\N	\N	11
67782507-d5f4-46b1-841e-519e467dfb50	7d2077bf-35cb-4c1b-9629-ca1ea01a3e0d	2026-06-06	1000.00	0.00	PENDING	\N	\N	11
536970ed-0c7d-4a83-98e5-263ee3c9fe42	7d2077bf-35cb-4c1b-9629-ca1ea01a3e0d	2026-07-06	1000.00	0.00	PENDING	\N	\N	11
d490805c-d139-4e96-9ebc-0347d9f02388	7d2077bf-35cb-4c1b-9629-ca1ea01a3e0d	2026-08-06	1000.00	0.00	PENDING	\N	\N	11
84593963-b648-4d8c-a7a1-b3b880691366	7d2077bf-35cb-4c1b-9629-ca1ea01a3e0d	2026-09-06	1000.00	0.00	PENDING	\N	\N	11
c2eea317-dcee-47a5-a49f-c725c7c0b513	7d2077bf-35cb-4c1b-9629-ca1ea01a3e0d	2026-10-06	1000.00	0.00	PENDING	\N	\N	11
1e18cdd5-9062-44b6-88c1-7edde750b04a	7d2077bf-35cb-4c1b-9629-ca1ea01a3e0d	2026-11-06	1000.00	0.00	PENDING	\N	\N	11
51bad901-8026-4557-a77d-eb20321b92f9	7d2077bf-35cb-4c1b-9629-ca1ea01a3e0d	2026-12-06	1000.00	0.00	PENDING	\N	\N	11
ad8f4fc9-c9cb-47f3-b958-630722ac7828	7d2077bf-35cb-4c1b-9629-ca1ea01a3e0d	2027-01-06	1000.00	0.00	PENDING	\N	\N	11
0881da8f-f34c-48ef-96f4-238376b2a0e1	7d2077bf-35cb-4c1b-9629-ca1ea01a3e0d	2027-02-06	1000.00	0.00	PENDING	\N	\N	11
e73289ff-8da7-43d6-916a-1f18ac2e775d	7d2077bf-35cb-4c1b-9629-ca1ea01a3e0d	2027-03-06	1000.00	0.00	PENDING	\N	\N	11
a31162d0-a7b6-4181-910a-6919a931fb90	7d2077bf-35cb-4c1b-9629-ca1ea01a3e0d	2027-04-06	1000.00	0.00	PENDING	\N	\N	11
2e691d44-72de-4da8-82fe-79595d2de7b0	7d2077bf-35cb-4c1b-9629-ca1ea01a3e0d	2027-05-06	1000.00	0.00	PENDING	\N	\N	11
89acac54-8795-4fd4-8239-7eb6540e3626	7d2077bf-35cb-4c1b-9629-ca1ea01a3e0d	2027-06-06	1000.00	0.00	PENDING	\N	\N	11
e8e0cfce-c0f8-44ae-a527-76535c130b63	7d2077bf-35cb-4c1b-9629-ca1ea01a3e0d	2027-07-06	1000.00	0.00	PENDING	\N	\N	11
e766bc3b-9da8-4677-a389-7e9be52c0183	7d2077bf-35cb-4c1b-9629-ca1ea01a3e0d	2027-08-06	1000.00	0.00	PENDING	\N	\N	11
825f7ef1-9709-4ba7-8044-00302e3f5091	7d2077bf-35cb-4c1b-9629-ca1ea01a3e0d	2027-09-06	1000.00	0.00	PENDING	\N	\N	11
ea48ba22-a4d9-4dea-b2e1-f84096ff59e2	7d2077bf-35cb-4c1b-9629-ca1ea01a3e0d	2027-10-06	1000.00	0.00	PENDING	\N	\N	11
c4ef5b24-e8a3-432f-97a5-d6ebd6026904	7d2077bf-35cb-4c1b-9629-ca1ea01a3e0d	2027-11-06	1000.00	0.00	PENDING	\N	\N	11
3cfd8728-9ec8-42ce-a327-9979580bac85	7d2077bf-35cb-4c1b-9629-ca1ea01a3e0d	2027-12-06	1000.00	0.00	PENDING	\N	\N	11
53adc5ae-2711-422c-90a2-ac77601e901e	7d2077bf-35cb-4c1b-9629-ca1ea01a3e0d	2028-01-06	1000.00	0.00	PENDING	\N	\N	11
6e4aa3a3-9d7f-4e22-aff1-1c7e35f9bd71	7d2077bf-35cb-4c1b-9629-ca1ea01a3e0d	2026-01-06	1000.00	1000.00	PAID	\N	\N	11
3220b9a2-e8fe-463d-9106-c036e67474fc	319c190f-9504-4de4-b24b-3c7dff2f61f0	2026-02-19	1000.00	0.00	PENDING	\N	\N	10
4fecd427-eeeb-45f3-a24a-d3bf7b3b5eda	319c190f-9504-4de4-b24b-3c7dff2f61f0	2026-03-19	1000.00	0.00	PENDING	\N	\N	10
bd0f6504-b9bb-47fd-9999-1f389d83cf3a	319c190f-9504-4de4-b24b-3c7dff2f61f0	2026-04-19	1000.00	0.00	PENDING	\N	\N	10
bbf0acb1-e375-4f87-b8c4-35302b51d9c8	319c190f-9504-4de4-b24b-3c7dff2f61f0	2026-05-19	1000.00	0.00	PENDING	\N	\N	10
1e4a0832-df39-4beb-9bb3-32c122dd385f	532a6ee1-8b69-469d-84a4-acdf25ca014c	2026-01-07	30.00	30.00	PAID	\N	\N	11
48cac529-b4ec-43cf-8ecc-ba5db525f2ca	e651d84d-2551-4cf8-821c-fd84859a259b	2026-02-15	200.00	0.00	PENDING	\N	\N	11
00bb1962-9753-40a7-82dc-3070b9296221	e651d84d-2551-4cf8-821c-fd84859a259b	2026-03-15	200.00	0.00	PENDING	\N	\N	11
87139e42-b30b-4100-9cbb-d7e916ac1c94	e651d84d-2551-4cf8-821c-fd84859a259b	2026-04-15	200.00	0.00	PENDING	\N	\N	11
184ecc87-c6e0-4c47-9af8-5c8d3bee9e95	e651d84d-2551-4cf8-821c-fd84859a259b	2026-05-15	200.00	0.00	PENDING	\N	\N	11
4c255321-3221-4ebd-8ec8-bf1792b53439	e651d84d-2551-4cf8-821c-fd84859a259b	2026-06-15	200.00	0.00	PENDING	\N	\N	11
55f008dc-860c-41a8-8a0e-4b4fe1a555d0	4108597c-02a5-4815-b3fe-1c229bcd5b50	2026-02-15	200.00	0.00	PENDING	\N	\N	11
872d8ef9-1606-41bb-8c6b-893fcda2be3b	4108597c-02a5-4815-b3fe-1c229bcd5b50	2026-03-15	200.00	0.00	PENDING	\N	\N	11
0b70553a-8122-4473-9b3f-cfd60c8e9f2a	4108597c-02a5-4815-b3fe-1c229bcd5b50	2026-04-15	200.00	0.00	PENDING	\N	\N	11
ebb8712c-bc3e-4034-9a4d-b7e13c8fd5b1	4108597c-02a5-4815-b3fe-1c229bcd5b50	2026-05-15	200.00	0.00	PENDING	\N	\N	11
dfb48e3a-bc67-46c4-882e-a4c4a70a0991	4108597c-02a5-4815-b3fe-1c229bcd5b50	2026-06-15	200.00	0.00	PENDING	\N	\N	11
4f341095-8f2f-473d-a4fb-1e56d171669d	b7fd0ace-a67c-46d0-9be3-98447a1c3bf5	2026-02-15	200.00	0.00	PENDING	\N	\N	11
189ecc45-a56d-4804-af22-1c1c32e911f5	b7fd0ace-a67c-46d0-9be3-98447a1c3bf5	2026-03-15	200.00	0.00	PENDING	\N	\N	11
e6b8ac83-7e0d-46d0-95dc-b58b0e78637b	b7fd0ace-a67c-46d0-9be3-98447a1c3bf5	2026-04-15	200.00	0.00	PENDING	\N	\N	11
bc2ec651-8f82-44a6-ae86-7ceb786381ed	b7fd0ace-a67c-46d0-9be3-98447a1c3bf5	2026-05-15	200.00	0.00	PENDING	\N	\N	11
33db27b7-9b80-4f07-80ec-1ecc3b89a72b	b7fd0ace-a67c-46d0-9be3-98447a1c3bf5	2026-06-15	200.00	0.00	PENDING	\N	\N	11
892e8672-1e6e-483c-855a-1e9c4da1297e	319c190f-9504-4de4-b24b-3c7dff2f61f0	2026-01-19	1000.00	1000.00	PAID	\N	\N	10
6fdf363e-6bdd-4d21-9e69-b65330769dc8	088f48d9-c503-4931-8bf3-cd643847ae58	2026-02-01	1000.00	0.00	PENDING	\N	\N	11
1cfe2e84-c789-4822-8968-5022bba79529	088f48d9-c503-4931-8bf3-cd643847ae58	2026-03-01	1000.00	0.00	PENDING	\N	\N	11
2f6aeddb-381b-4414-813f-1dfac7185329	088f48d9-c503-4931-8bf3-cd643847ae58	2026-04-01	1000.00	0.00	PENDING	\N	\N	11
4855f42e-08cb-4c2f-b0b5-0c0897e3b242	088f48d9-c503-4931-8bf3-cd643847ae58	2026-05-01	1000.00	0.00	PENDING	\N	\N	11
6801123a-c6db-4a6a-b4af-a601784e59f1	088f48d9-c503-4931-8bf3-cd643847ae58	2026-06-01	1000.00	0.00	PENDING	\N	\N	11
ef69b4f5-9d79-4b72-8ba0-32c265e3585f	088f48d9-c503-4931-8bf3-cd643847ae58	2026-07-01	1000.00	0.00	PENDING	\N	\N	11
0eaa6ec2-b668-4a42-a655-d5e87ec5092f	088f48d9-c503-4931-8bf3-cd643847ae58	2026-08-01	1000.00	0.00	PENDING	\N	\N	11
1b5eb4d2-91c6-4d7e-8531-26b1d8a78254	088f48d9-c503-4931-8bf3-cd643847ae58	2026-09-01	1000.00	0.00	PENDING	\N	\N	11
421b2b53-082d-436a-a307-ea4223adc0ac	088f48d9-c503-4931-8bf3-cd643847ae58	2026-10-01	1000.00	0.00	PENDING	\N	\N	11
261ff7c9-9b4e-4560-b507-a8a6cb43e434	088f48d9-c503-4931-8bf3-cd643847ae58	2026-11-01	1000.00	0.00	PENDING	\N	\N	11
1bad5abd-b678-400c-b18f-32248e95314f	088f48d9-c503-4931-8bf3-cd643847ae58	2026-12-01	1000.00	0.00	PENDING	\N	\N	11
82647fae-2394-49c7-aea8-b146dec1f252	088f48d9-c503-4931-8bf3-cd643847ae58	2027-01-01	1000.00	0.00	PENDING	\N	\N	11
16547a58-57ef-48ad-b1f1-f8c00ae38e8e	088f48d9-c503-4931-8bf3-cd643847ae58	2027-02-01	1000.00	0.00	PENDING	\N	\N	11
369e94ec-d940-44cb-b017-27562cb5a997	088f48d9-c503-4931-8bf3-cd643847ae58	2027-03-01	1000.00	0.00	PENDING	\N	\N	11
21646cbf-678b-4beb-a59f-6dc563667daa	088f48d9-c503-4931-8bf3-cd643847ae58	2027-04-01	1000.00	0.00	PENDING	\N	\N	11
10a9f5e7-1fb6-4c9f-aa6a-04fa432b9b1b	088f48d9-c503-4931-8bf3-cd643847ae58	2027-05-01	1000.00	0.00	PENDING	\N	\N	11
2125582b-79d3-4e65-8782-6c3d660e0290	088f48d9-c503-4931-8bf3-cd643847ae58	2027-06-01	1000.00	0.00	PENDING	\N	\N	11
908d64d5-16f5-4343-bb14-a5ba9b8daa37	088f48d9-c503-4931-8bf3-cd643847ae58	2027-07-01	1000.00	0.00	PENDING	\N	\N	11
1560ea5e-6c8a-4741-8075-b48cc5d61bd8	088f48d9-c503-4931-8bf3-cd643847ae58	2027-08-01	1000.00	0.00	PENDING	\N	\N	11
c295dcd2-283e-4dc4-bcd2-11530a81b614	088f48d9-c503-4931-8bf3-cd643847ae58	2027-09-01	1000.00	0.00	PENDING	\N	\N	11
ca878d38-11f9-4cb3-b72b-de2f571fc46b	088f48d9-c503-4931-8bf3-cd643847ae58	2027-10-01	1000.00	0.00	PENDING	\N	\N	11
cf169efd-52e9-49ce-9fa7-5e242fb8fc06	088f48d9-c503-4931-8bf3-cd643847ae58	2027-11-01	1000.00	0.00	PENDING	\N	\N	11
c62b53f0-9d20-407a-a219-d165cabc4a92	088f48d9-c503-4931-8bf3-cd643847ae58	2027-12-01	1000.00	0.00	PENDING	\N	\N	11
c3eed8f1-7413-4531-a19a-3231d44afd86	088f48d9-c503-4931-8bf3-cd643847ae58	2028-01-01	1000.00	0.00	PENDING	\N	\N	11
e8863b87-74ec-4007-b921-d77eba522a8e	088f48d9-c503-4931-8bf3-cd643847ae58	2028-02-01	1000.00	0.00	PENDING	\N	\N	11
dbcf37fe-6822-40d6-a995-fdc039cd4eb7	80d74015-ad29-49b2-a6a5-808c41b9fe26	2026-02-01	1000.00	0.00	PENDING	\N	\N	10
531b1af4-4ecf-42f9-8f27-32b3330d53fe	80d74015-ad29-49b2-a6a5-808c41b9fe26	2026-03-01	1000.00	0.00	PENDING	\N	\N	10
73ac4af7-4741-4ed0-947c-d02541556c2a	80d74015-ad29-49b2-a6a5-808c41b9fe26	2026-04-01	1000.00	0.00	PENDING	\N	\N	10
7115da21-eae2-4812-81e0-73584090bd9c	80d74015-ad29-49b2-a6a5-808c41b9fe26	2026-05-01	1000.00	0.00	PENDING	\N	\N	10
025c2cb5-2ce2-4137-bc14-0b070a7e9665	80d74015-ad29-49b2-a6a5-808c41b9fe26	2026-06-01	1000.00	0.00	PENDING	\N	\N	10
b832ce08-428b-4a78-a224-6c048e8f671b	80d74015-ad29-49b2-a6a5-808c41b9fe26	2026-07-01	1000.00	0.00	PENDING	\N	\N	10
4d34f493-bce6-496c-8a9c-4cfe6c75ff50	80d74015-ad29-49b2-a6a5-808c41b9fe26	2026-08-01	1000.00	0.00	PENDING	\N	\N	10
40cdb58b-1f48-49bb-a095-495a0bf02619	80d74015-ad29-49b2-a6a5-808c41b9fe26	2026-09-01	1000.00	0.00	PENDING	\N	\N	10
100e2415-fec5-40d0-a6c8-fb15b36c1534	80d74015-ad29-49b2-a6a5-808c41b9fe26	2026-10-01	1000.00	0.00	PENDING	\N	\N	10
b814017c-c400-4770-be5b-ad9edc8b6402	80d74015-ad29-49b2-a6a5-808c41b9fe26	2026-11-01	1000.00	0.00	PENDING	\N	\N	10
13377ac5-a6f6-4400-af5f-3514da8d79af	80d74015-ad29-49b2-a6a5-808c41b9fe26	2026-12-01	1000.00	0.00	PENDING	\N	\N	10
02dd63ee-658c-4d30-a3e3-4b1557f78445	80d74015-ad29-49b2-a6a5-808c41b9fe26	2027-01-01	1000.00	0.00	PENDING	\N	\N	10
df7d0cce-7af8-4abe-96ef-758ad5293ca7	80d74015-ad29-49b2-a6a5-808c41b9fe26	2027-02-01	1000.00	0.00	PENDING	\N	\N	10
f3e23e87-52a3-42d7-875d-e9ed16f242bf	80d74015-ad29-49b2-a6a5-808c41b9fe26	2027-03-01	1000.00	0.00	PENDING	\N	\N	10
23d7b98e-447a-4bed-bf17-34a7ed1005c8	7d2077bf-35cb-4c1b-9629-ca1ea01a3e0d	2026-02-06	1000.00	1000.00	PAID	\N	\N	11
f4c72e72-1deb-4076-bc40-e80877360b97	7d2077bf-35cb-4c1b-9629-ca1ea01a3e0d	2026-03-06	1000.00	1000.00	PAID	\N	\N	11
529ede07-76ff-48c7-b609-6ada8777c7ef	7d2077bf-35cb-4c1b-9629-ca1ea01a3e0d	2026-04-06	1000.00	1000.00	PAID	\N	\N	11
924b4c6d-06c5-4e66-b98b-4dbac689215d	80d74015-ad29-49b2-a6a5-808c41b9fe26	2027-04-01	1000.00	0.00	PENDING	\N	\N	10
c5ebb703-9c11-411e-8093-44506dec0473	80d74015-ad29-49b2-a6a5-808c41b9fe26	2027-05-01	1000.00	0.00	PENDING	\N	\N	10
2aee4f6d-32ee-436f-bbe8-37a4679406bf	80d74015-ad29-49b2-a6a5-808c41b9fe26	2027-06-01	1000.00	0.00	PENDING	\N	\N	10
ae190994-f80a-4f3f-8f92-68d35984782d	80d74015-ad29-49b2-a6a5-808c41b9fe26	2027-07-01	1000.00	0.00	PENDING	\N	\N	10
5018aa82-91d9-47ed-8d9f-7a246e7223d8	80d74015-ad29-49b2-a6a5-808c41b9fe26	2027-08-01	1000.00	0.00	PENDING	\N	\N	10
029a3b87-2a79-4ec9-b10d-cca8ae4c07f1	80d74015-ad29-49b2-a6a5-808c41b9fe26	2027-09-01	1000.00	0.00	PENDING	\N	\N	10
bc28711c-072a-49a2-9422-a56904b941ce	80d74015-ad29-49b2-a6a5-808c41b9fe26	2027-10-01	1000.00	0.00	PENDING	\N	\N	10
14a8a5a9-f648-455b-a3ae-8f0978911ed6	80d74015-ad29-49b2-a6a5-808c41b9fe26	2027-11-01	1000.00	0.00	PENDING	\N	\N	10
a6d68295-be23-41e6-a406-91f4677e4cc5	80d74015-ad29-49b2-a6a5-808c41b9fe26	2027-12-01	1000.00	0.00	PENDING	\N	\N	10
88040fb5-a986-438c-8f3f-2c8c75fd0295	80d74015-ad29-49b2-a6a5-808c41b9fe26	2028-01-01	1000.00	0.00	PENDING	\N	\N	10
c3efb7d2-1269-4350-83e3-6548f44c04a1	80d74015-ad29-49b2-a6a5-808c41b9fe26	2028-02-01	1000.00	0.00	PENDING	\N	\N	10
42b55662-be03-417a-9f4c-d210244c39dc	6b0d57b5-b41b-4cad-9952-9e07f3f51d9a	2026-02-15	200.00	0.00	PENDING	\N	\N	11
fb9fc067-9766-4f90-aef2-2f0c92523120	6b0d57b5-b41b-4cad-9952-9e07f3f51d9a	2026-03-15	200.00	0.00	PENDING	\N	\N	11
62920ace-7cde-42a6-af68-6a706a393461	6b0d57b5-b41b-4cad-9952-9e07f3f51d9a	2026-04-15	200.00	0.00	PENDING	\N	\N	11
571c782b-d200-4a3f-a80d-530a5d968dfb	6b0d57b5-b41b-4cad-9952-9e07f3f51d9a	2026-05-15	200.00	0.00	PENDING	\N	\N	11
825c8dcb-2c3d-4fe8-a901-61ee24cd1c1b	6b0d57b5-b41b-4cad-9952-9e07f3f51d9a	2026-06-15	200.00	0.00	PENDING	\N	\N	11
7f70e469-8428-4cd6-b0b8-0495fcc9d05a	dd1ecf4c-f22b-4e7b-bb98-ff0fd5fd6294	2026-02-15	200.00	0.00	PENDING	\N	\N	11
623425f3-e8f6-4123-acea-4ad836e1bd7b	dd1ecf4c-f22b-4e7b-bb98-ff0fd5fd6294	2026-03-15	200.00	0.00	PENDING	\N	\N	11
4cf8ae4b-d6ab-425e-8a33-7b3ae672bd39	dd1ecf4c-f22b-4e7b-bb98-ff0fd5fd6294	2026-04-15	200.00	0.00	PENDING	\N	\N	11
72b35e2a-1afe-436f-a261-89b6d056b8f6	dd1ecf4c-f22b-4e7b-bb98-ff0fd5fd6294	2026-05-15	200.00	0.00	PENDING	\N	\N	11
5abdc1cd-1a98-4bba-a739-f9039c7a49c0	dd1ecf4c-f22b-4e7b-bb98-ff0fd5fd6294	2026-06-15	200.00	0.00	PENDING	\N	\N	11
56964c16-8d78-4f48-9fbc-2a2a1392d58e	97e351f8-a76d-48d5-81d6-b2ef3e15158b	2026-02-21	1000.00	0.00	PENDING	\N	\N	10
97e4af72-10bb-4286-ab34-5ef1673794a7	97e351f8-a76d-48d5-81d6-b2ef3e15158b	2026-03-21	1000.00	0.00	PENDING	\N	\N	10
8e0a0fb3-ee41-4f2f-8890-a85c24524651	97e351f8-a76d-48d5-81d6-b2ef3e15158b	2026-04-21	1000.00	0.00	PENDING	\N	\N	10
ef788445-f2fa-4acd-81e4-cc0fc514c541	97e351f8-a76d-48d5-81d6-b2ef3e15158b	2026-05-21	1000.00	0.00	PENDING	\N	\N	10
3c7c791e-f9d4-4c18-b4b2-19df557f9919	97e351f8-a76d-48d5-81d6-b2ef3e15158b	2026-06-21	1000.00	0.00	PENDING	\N	\N	10
87ecc6c1-a8f5-44b5-9068-a7a459bf641c	97e351f8-a76d-48d5-81d6-b2ef3e15158b	2026-07-21	1000.00	0.00	PENDING	\N	\N	10
655ccb42-40f5-46f3-9aad-93ebac0801f1	97e351f8-a76d-48d5-81d6-b2ef3e15158b	2026-08-21	1000.00	0.00	PENDING	\N	\N	10
b1112b99-1cb8-4338-aaef-6c2bc9649db3	97e351f8-a76d-48d5-81d6-b2ef3e15158b	2026-09-21	1000.00	0.00	PENDING	\N	\N	10
128ecc7d-e23e-48bc-a947-e6eb2dc6c6a2	97e351f8-a76d-48d5-81d6-b2ef3e15158b	2026-10-21	1000.00	0.00	PENDING	\N	\N	10
ec370f23-c1e0-4aaa-8a55-a66351425af6	97e351f8-a76d-48d5-81d6-b2ef3e15158b	2026-11-21	1000.00	0.00	PENDING	\N	\N	10
574d70d5-6f48-4490-9d40-96e85155c426	97e351f8-a76d-48d5-81d6-b2ef3e15158b	2026-12-21	1000.00	0.00	PENDING	\N	\N	10
3b675a0c-20e9-4d35-afb6-a5672bf0f627	97e351f8-a76d-48d5-81d6-b2ef3e15158b	2027-01-21	1000.00	0.00	PENDING	\N	\N	10
e3cb5636-7b25-4aa5-970f-db11ecb62c95	97e351f8-a76d-48d5-81d6-b2ef3e15158b	2027-02-21	1000.00	0.00	PENDING	\N	\N	10
567534e6-6d3c-46c9-8517-acf69131696f	97e351f8-a76d-48d5-81d6-b2ef3e15158b	2027-03-21	1000.00	0.00	PENDING	\N	\N	10
9c01e518-db2a-4564-9bec-399882bc72c7	97e351f8-a76d-48d5-81d6-b2ef3e15158b	2027-04-21	1000.00	0.00	PENDING	\N	\N	10
6c8dfd47-3e72-403c-9672-b30fd1ea2a15	97e351f8-a76d-48d5-81d6-b2ef3e15158b	2027-05-21	1000.00	0.00	PENDING	\N	\N	10
7ac9517a-6a74-4043-ba7f-3a04cd519d5e	97e351f8-a76d-48d5-81d6-b2ef3e15158b	2027-06-21	1000.00	0.00	PENDING	\N	\N	10
d8ac4f4c-4c1a-4ef6-9dac-26cfce1b34f4	97e351f8-a76d-48d5-81d6-b2ef3e15158b	2027-07-21	1000.00	0.00	PENDING	\N	\N	10
3d9f4f67-4d28-4b50-b7ef-5d17c967edbb	97e351f8-a76d-48d5-81d6-b2ef3e15158b	2027-08-21	1000.00	0.00	PENDING	\N	\N	10
f11b8e9f-b5e9-42bd-b479-7df2a69bd294	97e351f8-a76d-48d5-81d6-b2ef3e15158b	2027-09-21	1000.00	0.00	PENDING	\N	\N	10
205d40ef-5738-4aa3-9c0f-8310e164bc33	97e351f8-a76d-48d5-81d6-b2ef3e15158b	2027-10-21	1000.00	0.00	PENDING	\N	\N	10
58024b8c-1c6a-42c6-9a87-d23b03d220c7	97e351f8-a76d-48d5-81d6-b2ef3e15158b	2027-11-21	1000.00	0.00	PENDING	\N	\N	10
7b1f32fa-f548-4b97-9336-63f5d4299e12	97e351f8-a76d-48d5-81d6-b2ef3e15158b	2027-12-21	1000.00	0.00	PENDING	\N	\N	10
0824ad69-7484-4ce6-8beb-0e769dfe5513	97e351f8-a76d-48d5-81d6-b2ef3e15158b	2028-01-21	1000.00	0.00	PENDING	\N	\N	10
23107b75-328b-497d-9dae-cfa44f859b52	97e351f8-a76d-48d5-81d6-b2ef3e15158b	2026-01-21	1000.00	1000.00	PAID	\N	\N	10
\.


--
-- Data for Name: core_role; Type: TABLE DATA; Schema: public; Owner: yaelfarber
--

COPY public.core_role (role_id, name, description, created_at) FROM stdin;
a3c4938e-03db-4364-a931-b8f942158a03	Admin	System administrator	2025-12-05 10:40:57.96369+02
4a38823a-11b8-419d-a91b-d3b8a162b132	Trustee	Community trustee	2025-12-05 10:40:57.967653+02
941eae3d-ca30-4d87-9474-5b55d5e8b219	Borrower	Loan borrower	2025-12-05 10:40:57.969367+02
c38fa941-0ed0-4c26-8770-135b1485f9c5	Donor	System donor	2025-12-05 10:40:57.97082+02
\.


--
-- Data for Name: core_trustee; Type: TABLE DATA; Schema: public; Owner: yaelfarber
--

COPY public.core_trustee (trustee_id, community, notes, user_id) FROM stdin;
00000000-0000-0000-0000-000000000001	רמות	נאמן ראשי	3
00000000-0000-0000-0000-000000000002	הר נוף		4
00000000-0000-0000-0000-000000000003	פסגת זאב		5
\.


--
-- Data for Name: core_userprofile; Type: TABLE DATA; Schema: public; Owner: yaelfarber
--

COPY public.core_userprofile (id, phone, role_id, user_id) FROM stdin;
1	050-1000001	a3c4938e-03db-4364-a931-b8f942158a03	1
2	050-1000002	a3c4938e-03db-4364-a931-b8f942158a03	2
3	050-2000001	4a38823a-11b8-419d-a91b-d3b8a162b132	3
4	050-2000002	4a38823a-11b8-419d-a91b-d3b8a162b132	4
5	050-2000003	4a38823a-11b8-419d-a91b-d3b8a162b132	5
6	050-3000001	941eae3d-ca30-4d87-9474-5b55d5e8b219	6
7	050-3000002	941eae3d-ca30-4d87-9474-5b55d5e8b219	7
8	050-3000003	941eae3d-ca30-4d87-9474-5b55d5e8b219	8
9	050-4000001	c38fa941-0ed0-4c26-8770-135b1485f9c5	9
10	050-4000002	c38fa941-0ed0-4c26-8770-135b1485f9c5	10
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: yaelfarber
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: yaelfarber
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	core	role
8	core	borrower
9	core	trustee
10	core	loanstandingorder
11	core	loanchecks
12	core	userprofile
13	core	payment
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: yaelfarber
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-12-01 13:01:20.840806+02
2	auth	0001_initial	2025-12-01 13:01:20.899605+02
3	admin	0001_initial	2025-12-01 13:01:20.918912+02
4	admin	0002_logentry_remove_auto_add	2025-12-01 13:01:20.927916+02
5	admin	0003_logentry_add_action_flag_choices	2025-12-01 13:01:20.934852+02
6	contenttypes	0002_remove_content_type_name	2025-12-01 13:01:20.948265+02
7	auth	0002_alter_permission_name_max_length	2025-12-01 13:01:20.957266+02
8	auth	0003_alter_user_email_max_length	2025-12-01 13:01:20.964223+02
9	auth	0004_alter_user_username_opts	2025-12-01 13:01:20.97313+02
10	auth	0005_alter_user_last_login_null	2025-12-01 13:01:20.980626+02
11	auth	0006_require_contenttypes_0002	2025-12-01 13:01:20.981848+02
12	auth	0007_alter_validators_add_error_messages	2025-12-01 13:01:20.990001+02
13	auth	0008_alter_user_username_max_length	2025-12-01 13:01:21.001659+02
14	auth	0009_alter_user_last_name_max_length	2025-12-01 13:01:21.00947+02
15	auth	0010_alter_group_name_max_length	2025-12-01 13:01:21.018767+02
16	auth	0011_update_proxy_permissions	2025-12-01 13:01:21.02502+02
17	auth	0012_alter_user_first_name_max_length	2025-12-01 13:01:21.033693+02
18	core	0001_initial	2025-12-01 13:01:21.130109+02
19	sessions	0001_initial	2025-12-01 13:01:21.139568+02
20	core	0002_add_default_roles	2025-12-05 10:40:57.971476+02
21	core	0003_borrower_email_borrower_first_name_and_more	2025-12-31 10:59:24.08703+02
22	core	0004_payment	2026-01-06 21:39:46.516278+02
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: yaelfarber
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
08j7rxjesre61jtoszuupoqeuj6z6psb	.eJxVjMsOwiAQRf-FtSED5VFcuvcbCMNMpWogKe3K-O_apAvd3nPOfYmYtrXErfMSZxJnoZQ4_Y6Y8oPrTuie6q3J3Oq6zCh3RR60y2sjfl4O9--gpF6-tbcB0bALAGmyanTGgQEEGgmyJa0ZB6TMaoIhoPaBwCd0LnvjAViJ9wf52je-:1vXP6e:Iyu1yKPiL0bCi_o61zC36qrWoHcmeHSknNcnHgnEmWs	2026-01-04 21:28:40.841347+02
yf1qrrjpuo2p2z0xjzbg6g5a8yswmxif	.eJxVjMsOwiAQRf-FtSED5VFcuvcbCMNMpWogKe3K-O_apAvd3nPOfYmYtrXErfMSZxJnoZQ4_Y6Y8oPrTuie6q3J3Oq6zCh3RR60y2sjfl4O9--gpF6-tbcB0bALAGmyanTGgQEEGgmyJa0ZB6TMaoIhoPaBwCd0LnvjAViJ9wf52je-:1vXPFI:HZU-I561uXyOg0RqzZyL9sFz7FpKodIRa2QoxBjA63w	2026-01-04 21:37:36.010786+02
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: yaelfarber
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: yaelfarber
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: yaelfarber
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 52, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: yaelfarber
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: yaelfarber
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 11, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: yaelfarber
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: core_userprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: yaelfarber
--

SELECT pg_catalog.setval('public.core_userprofile_id_seq', 10, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: yaelfarber
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: yaelfarber
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 13, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: yaelfarber
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 22, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: core_borrower core_borrower_id_number_key; Type: CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.core_borrower
    ADD CONSTRAINT core_borrower_id_number_key UNIQUE (id_number);


--
-- Name: core_borrower core_borrower_pkey; Type: CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.core_borrower
    ADD CONSTRAINT core_borrower_pkey PRIMARY KEY (borrower_id);


--
-- Name: core_borrower core_borrower_user_id_key; Type: CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.core_borrower
    ADD CONSTRAINT core_borrower_user_id_key UNIQUE (user_id);


--
-- Name: core_loanchecks core_loanchecks_pkey; Type: CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.core_loanchecks
    ADD CONSTRAINT core_loanchecks_pkey PRIMARY KEY (loan_id);


--
-- Name: core_loanstandingorder core_loanstandingorder_pkey; Type: CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.core_loanstandingorder
    ADD CONSTRAINT core_loanstandingorder_pkey PRIMARY KEY (loan_id);


--
-- Name: core_payment core_payment_pkey; Type: CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.core_payment
    ADD CONSTRAINT core_payment_pkey PRIMARY KEY (id);


--
-- Name: core_role core_role_name_key; Type: CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.core_role
    ADD CONSTRAINT core_role_name_key UNIQUE (name);


--
-- Name: core_role core_role_pkey; Type: CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.core_role
    ADD CONSTRAINT core_role_pkey PRIMARY KEY (role_id);


--
-- Name: core_trustee core_trustee_pkey; Type: CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.core_trustee
    ADD CONSTRAINT core_trustee_pkey PRIMARY KEY (trustee_id);


--
-- Name: core_trustee core_trustee_user_id_key; Type: CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.core_trustee
    ADD CONSTRAINT core_trustee_user_id_key UNIQUE (user_id);


--
-- Name: core_userprofile core_userprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.core_userprofile
    ADD CONSTRAINT core_userprofile_pkey PRIMARY KEY (id);


--
-- Name: core_userprofile core_userprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.core_userprofile
    ADD CONSTRAINT core_userprofile_user_id_key UNIQUE (user_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: yaelfarber
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: yaelfarber
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: yaelfarber
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: yaelfarber
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: yaelfarber
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: yaelfarber
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: yaelfarber
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: yaelfarber
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: yaelfarber
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: core_borrower_id_number_67140753_like; Type: INDEX; Schema: public; Owner: yaelfarber
--

CREATE INDEX core_borrower_id_number_67140753_like ON public.core_borrower USING btree (id_number varchar_pattern_ops);


--
-- Name: core_borrower_trustee_id_54c86d86; Type: INDEX; Schema: public; Owner: yaelfarber
--

CREATE INDEX core_borrower_trustee_id_54c86d86 ON public.core_borrower USING btree (trustee_id);


--
-- Name: core_loanchecks_borrower_id_dfff3d90; Type: INDEX; Schema: public; Owner: yaelfarber
--

CREATE INDEX core_loanchecks_borrower_id_dfff3d90 ON public.core_loanchecks USING btree (borrower_id);


--
-- Name: core_loanchecks_trustee_id_7d165198; Type: INDEX; Schema: public; Owner: yaelfarber
--

CREATE INDEX core_loanchecks_trustee_id_7d165198 ON public.core_loanchecks USING btree (trustee_id);


--
-- Name: core_loanstandingorder_borrower_id_bdbfc542; Type: INDEX; Schema: public; Owner: yaelfarber
--

CREATE INDEX core_loanstandingorder_borrower_id_bdbfc542 ON public.core_loanstandingorder USING btree (borrower_id);


--
-- Name: core_loanstandingorder_trustee_id_9d7f4950; Type: INDEX; Schema: public; Owner: yaelfarber
--

CREATE INDEX core_loanstandingorder_trustee_id_9d7f4950 ON public.core_loanstandingorder USING btree (trustee_id);


--
-- Name: core_payment_content_type_id_d166e6c8; Type: INDEX; Schema: public; Owner: yaelfarber
--

CREATE INDEX core_payment_content_type_id_d166e6c8 ON public.core_payment USING btree (content_type_id);


--
-- Name: core_role_name_ca4cd9c7_like; Type: INDEX; Schema: public; Owner: yaelfarber
--

CREATE INDEX core_role_name_ca4cd9c7_like ON public.core_role USING btree (name varchar_pattern_ops);


--
-- Name: core_userprofile_role_id_391ca017; Type: INDEX; Schema: public; Owner: yaelfarber
--

CREATE INDEX core_userprofile_role_id_391ca017 ON public.core_userprofile USING btree (role_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: yaelfarber
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: yaelfarber
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: yaelfarber
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: yaelfarber
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_borrower core_borrower_trustee_id_54c86d86_fk_core_trustee_trustee_id; Type: FK CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.core_borrower
    ADD CONSTRAINT core_borrower_trustee_id_54c86d86_fk_core_trustee_trustee_id FOREIGN KEY (trustee_id) REFERENCES public.core_trustee(trustee_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_borrower core_borrower_user_id_b49f1115_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.core_borrower
    ADD CONSTRAINT core_borrower_user_id_b49f1115_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_loanchecks core_loanchecks_borrower_id_dfff3d90_fk_core_borr; Type: FK CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.core_loanchecks
    ADD CONSTRAINT core_loanchecks_borrower_id_dfff3d90_fk_core_borr FOREIGN KEY (borrower_id) REFERENCES public.core_borrower(borrower_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_loanchecks core_loanchecks_trustee_id_7d165198_fk_core_trustee_trustee_id; Type: FK CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.core_loanchecks
    ADD CONSTRAINT core_loanchecks_trustee_id_7d165198_fk_core_trustee_trustee_id FOREIGN KEY (trustee_id) REFERENCES public.core_trustee(trustee_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_loanstandingorder core_loanstandingord_borrower_id_bdbfc542_fk_core_borr; Type: FK CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.core_loanstandingorder
    ADD CONSTRAINT core_loanstandingord_borrower_id_bdbfc542_fk_core_borr FOREIGN KEY (borrower_id) REFERENCES public.core_borrower(borrower_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_loanstandingorder core_loanstandingord_trustee_id_9d7f4950_fk_core_trus; Type: FK CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.core_loanstandingorder
    ADD CONSTRAINT core_loanstandingord_trustee_id_9d7f4950_fk_core_trus FOREIGN KEY (trustee_id) REFERENCES public.core_trustee(trustee_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_payment core_payment_content_type_id_d166e6c8_fk_django_content_type_id; Type: FK CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.core_payment
    ADD CONSTRAINT core_payment_content_type_id_d166e6c8_fk_django_content_type_id FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_trustee core_trustee_user_id_126956c3_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.core_trustee
    ADD CONSTRAINT core_trustee_user_id_126956c3_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_userprofile core_userprofile_role_id_391ca017_fk_core_role_role_id; Type: FK CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.core_userprofile
    ADD CONSTRAINT core_userprofile_role_id_391ca017_fk_core_role_role_id FOREIGN KEY (role_id) REFERENCES public.core_role(role_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_userprofile core_userprofile_user_id_5141ad90_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.core_userprofile
    ADD CONSTRAINT core_userprofile_user_id_5141ad90_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: yaelfarber
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict 1rGwwGvwBFhfxZuDTDIJMXmGvlnex5DSWCgUp6Bv8KrNefEgkBGssUr1NYShukM

