# Generated by Django 5.2.8 on 2025-11-24 12:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('borrower_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_number', models.CharField(max_length=20, unique=True, verbose_name='תעודת זהות')),
                ('address', models.CharField(max_length=255, verbose_name='כתובת')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='borrower_profile', to=settings.AUTH_USER_MODEL, verbose_name='משתמש מקושר')),
            ],
            options={
                'verbose_name': 'לווה',
                'verbose_name_plural': 'לווים',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='סכום ההלוואה')),
                ('start_date', models.DateField(verbose_name='תאריך התחלה')),
                ('status', models.CharField(choices=[('PENDING', 'ממתין לאישור'), ('ACTIVE', 'פעיל'), ('PAID', 'שולם'), ('REJECTED', 'נדחה')], default='PENDING', max_length=20, verbose_name='סטטוס')),
                ('form_file', models.CharField(blank=True, max_length=255, null=True, verbose_name='קובץ טופס חתום')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('loan_type', models.CharField(max_length=50, verbose_name='סוג הלוואה')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='core.borrower', verbose_name='לווה')),
            ],
            options={
                'verbose_name': 'הלוואה',
                'verbose_name_plural': 'הלוואות',
            },
        ),
        migrations.CreateModel(
            name='Trustee',
            fields=[
                ('trustee_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('community', models.CharField(max_length=100, verbose_name='קהילה')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='הערות')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trustee_profile', to=settings.AUTH_USER_MODEL, verbose_name='משתמש מקושר')),
            ],
            options={
                'verbose_name': 'נאמן',
                'verbose_name_plural': 'נאמנים',
            },
        ),
        migrations.DeleteModel(
            name='TestEntry',
        ),
        migrations.CreateModel(
            name='LoanChecks',
            fields=[
                ('loan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.loan')),
                ('num_payments', models.IntegerField(verbose_name='מספר תשלומים')),
                ('check_details', models.TextField(blank=True, null=True, verbose_name="פרטי צ'קים")),
                ('predefined_schedule', models.BooleanField(default=True, verbose_name='לוח תשלומים מוגדר מראש?')),
            ],
            options={
                'verbose_name': "הלוואה (צ'קים)",
                'verbose_name_plural': "הלוואות (צ'קים)",
            },
            bases=('core.loan',),
        ),
        migrations.CreateModel(
            name='LoanStandingOrder',
            fields=[
                ('loan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.loan')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='סכום חודשי')),
                ('charge_day', models.IntegerField(verbose_name='יום חיוב בחודש')),
                ('stop_date', models.DateField(blank=True, null=True, verbose_name='תאריך עצירה')),
            ],
            options={
                'verbose_name': 'הלוואה (הוראת קבע)',
                'verbose_name_plural': 'הלוואות (הוראת קבע)',
            },
            bases=('core.loan',),
        ),
        migrations.AddField(
            model_name='loan',
            name='trustee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitored_loans', to='core.trustee', verbose_name='נאמן מפקח'),
        ),
        migrations.AddField(
            model_name='borrower',
            name='trustee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowers', to='core.trustee', verbose_name='נאמן מלווה'),
        ),
    ]
