# Generated by Django 5.2.8 on 2025-12-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_default_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
