# Generated by Django 5.2.8 on 2025-11-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_borrower_loan_trustee_delete_testentry_loanchecks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='form_file',
            field=models.FileField(blank=True, null=True, upload_to='loan_forms/', verbose_name='קובץ טופס חתום'),
        ),
    ]
