# Generated by Django 5.2.8 on 2026-01-04 13:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_borrower_email_borrower_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_date', models.DateField(verbose_name='תאריך לתשלום')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='סכום לתשלום')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='סכום ששולם')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20, verbose_name='סטטוס תשלום')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='תאריך תשלום בפועל')),
                ('check_number', models.CharField(blank=True, max_length=50, null=True, verbose_name="מספר צ'ק")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan_checks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.loanchecks')),
                ('loan_standing_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.loanstandingorder')),
            ],
        ),
    ]
