# Generated by Django 5.2.8 on 2026-09-06 09:32

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0004_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('audit_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(blank=True, default='', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('donation_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-donation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('donor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('reminder_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=20)),
                ('reminder_date', models.DateField()),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], max_length=20)),
                ('recipient_masked', models.CharField(blank=True, default='', max_length=50)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=100)),
                ('error_code', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderSettings',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('days_before', models.PositiveSmallIntegerField(default=3)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('BOTH', 'SMS + WhatsApp')], default='SMS', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='borrower',
            options={},
        ),
        migrations.AlterModelOptions(
            name='loanchecks',
            options={},
        ),
        migrations.AlterModelOptions(
            name='loanstandingorder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['due_date', 'id']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={},
        ),
        migrations.AlterModelOptions(
            name='trustee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.AddField(
            model_name='loanstandingorder',
            name='num_payments',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='payment',
            name='exception_note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_manual_exception',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='id_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='trustee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowers', to='core.trustee'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrower_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanchecks',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanchecks',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_loans', to='core.borrower'),
        ),
        migrations.AlterField(
            model_name='loanchecks',
            name='check_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanchecks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loanchecks',
            name='form_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.signed_form_upload_to),
        ),
        migrations.AlterField(
            model_name='loanchecks',
            name='num_payments',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='loanchecks',
            name='predefined_schedule',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='loanchecks',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='loanchecks',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('OVERDUE', 'Overdue'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanchecks',
            name='trustee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_monitored_loans', to='core.trustee'),
        ),
        migrations.AlterField(
            model_name='loanstandingorder',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanstandingorder',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_loans', to='core.borrower'),
        ),
        migrations.AlterField(
            model_name='loanstandingorder',
            name='charge_day',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='loanstandingorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loanstandingorder',
            name='form_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.signed_form_upload_to),
        ),
        migrations.AlterField(
            model_name='loanstandingorder',
            name='monthly_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanstandingorder',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='loanstandingorder',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('OVERDUE', 'Overdue'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanstandingorder',
            name='stop_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanstandingorder',
            name='trustee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_monitored_loans', to='core.trustee'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='due_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('LATE', 'Late')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='trustee',
            name='community',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trustee',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trustee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trustee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'due_date'), name='unique_payment_due_date_per_loan'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='core.donor'),
        ),
        migrations.AddField(
            model_name='reminderlog',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reminder_logs', to='core.payment'),
        ),
        migrations.AddConstraint(
            model_name='reminderlog',
            constraint=models.UniqueConstraint(fields=('payment', 'channel', 'reminder_date'), name='unique_daily_payment_reminder'),
        ),
    ]
