# Generated by Django 5.2.8 on 2026-09-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auditlog_donation_donor_reminderlog_remindersettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanstandingorder',
            name='standing_order_form_file',
            field=models.FileField(blank=True, null=True, upload_to='standing_order_forms/', verbose_name='Standing order authorization form'),
        ),
    ]
