# Generated by Django 5.2.8 on 2026-09-17 15:42

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_loanstandingorder_standing_order_form_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanstandingorder',
            name='standing_order_form_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.standing_order_form_upload_to, verbose_name='Standing order authorization form'),
        ),
    ]
